"""Add timezone support to DateTime columns

Revision ID: 6f4e0f5d81d7
Revises: 2247a14771e8
Create Date: 2026-03-13 13:15:58.182536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4e0f5d81d7'
down_revision: Union[str, Sequence[str], None] = '2247a14771e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
