"""add_blog_like_bookmark_and_user_follow_tables

Revision ID: dcce31859236
Revises: 6f4e0f5d81d7
Create Date: 2026-04-10 13:27:30.028759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcce31859236'
down_revision: Union[str, Sequence[str], None] = '6f4e0f5d81d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_bookmarks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blog_bookmarks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('blog_bookmarks', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('blog_bookmarks', 'blog_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_index('ix_blog_bookmarks_blog_id', 'blog_bookmarks', ['blog_id'], unique=False)
    op.create_index('ix_blog_bookmarks_user_id', 'blog_bookmarks', ['user_id'], unique=False)
    op.add_column('blog_likes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blog_likes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blog_likes', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('blog_likes', sa.Column('blog_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index('ix_blog_likes_blog_id', 'blog_likes', ['blog_id'], unique=False)
    op.create_index('ix_blog_likes_user_id', 'blog_likes', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_blog_like', 'blog_likes', ['user_id', 'blog_id'])
    op.create_foreign_key('fk_blog_likes_user_id_users', 'blog_likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_blog_likes_blog_id_blogs', 'blog_likes', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    op.add_column('blogs', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('blogs', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('blogs', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('summary', sa.String(length=500), nullable=True))
    op.add_column('blogs', sa.Column('cover_image', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('reading_time', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('bookmark_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('blogs', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('blogs', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('blogs', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.create_index('ix_blogs_user_id', 'blogs', ['user_id'], unique=False)
    op.create_unique_constraint('unique_user_blog_slug', 'blogs', ['user_id', 'slug'])
    op.add_column('user_follows', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_follows', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_follows', sa.Column('follower_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('user_follows', sa.Column('following_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_user_follows_id', table_name='user_follows')
    op.create_index('ix_user_follows_follower_id', 'user_follows', ['follower_id'], unique=False)
    op.create_index('ix_user_follows_following_id', 'user_follows', ['following_id'], unique=False)
    op.create_unique_constraint('uq_user_follows_follower_following', 'user_follows', ['follower_id', 'following_id'])
    op.create_foreign_key('fk_user_follow_follower_id_users', 'user_follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_follow_following_id_users', 'user_follows', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('headline', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('follower_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('is_private_account', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_private_account')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'follower_count')
    op.drop_column('users', 'github')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'website')
    op.drop_column('users', 'location')
    op.drop_column('users', 'headline')
    op.drop_column('users', 'display_name')
    op.drop_constraint('fk_user_follow_following_id_users', 'user_follows', type_='foreignkey')
    op.drop_constraint('fk_user_follow_follower_id_users', 'user_follows', type_='foreignkey')
    op.drop_constraint('uq_user_follows_follower_following', 'user_follows', type_='unique')
    op.drop_index('ix_user_follows_following_id', table_name='user_follows')
    op.drop_index('ix_user_follows_follower_id', table_name='user_follows')
    op.create_index('ix_user_follows_id', 'user_follows', ['id'], unique=False)
    op.drop_column('user_follows', 'following_id')
    op.drop_column('user_follows', 'follower_id')
    op.drop_column('user_follows', 'updated_at')
    op.drop_column('user_follows', 'created_at')
    op.drop_constraint('unique_user_blog_slug', 'blogs', type_='unique')
    op.drop_index('ix_blogs_user_id', table_name='blogs')
    op.drop_column('blogs', 'is_archived')
    op.drop_column('blogs', 'is_private')
    op.drop_column('blogs', 'is_locked')
    op.drop_column('blogs', 'is_featured')
    op.drop_column('blogs', 'bookmark_count')
    op.drop_column('blogs', 'comment_count')
    op.drop_column('blogs', 'like_count')
    op.drop_column('blogs', 'view_count')
    op.drop_column('blogs', 'reading_time')
    op.drop_column('blogs', 'cover_image')
    op.drop_column('blogs', 'summary')
    op.drop_column('blogs', 'published_at')
    op.drop_column('blogs', 'status')
    op.drop_column('blogs', 'slug')
    op.drop_constraint('fk_blog_likes_blog_id_blogs', 'blog_likes', type_='foreignkey')
    op.drop_constraint('fk_blog_likes_user_id_users', 'blog_likes', type_='foreignkey')
    op.drop_constraint('unique_user_blog_like', 'blog_likes', type_='unique')
    op.drop_index('ix_blog_likes_user_id', table_name='blog_likes')
    op.drop_index('ix_blog_likes_blog_id', table_name='blog_likes')
    op.drop_column('blog_likes', 'blog_id')
    op.drop_column('blog_likes', 'user_id')
    op.drop_column('blog_likes', 'updated_at')
    op.drop_column('blog_likes', 'created_at')
    op.drop_index('ix_blog_bookmarks_user_id', table_name='blog_bookmarks')
    op.drop_index('ix_blog_bookmarks_blog_id', table_name='blog_bookmarks')
    op.alter_column('blog_bookmarks', 'blog_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('blog_bookmarks', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('blog_bookmarks', 'updated_at')
    op.drop_column('blog_bookmarks', 'created_at')
    # ### end Alembic commands ###
